spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri:  https://github.com/shobhakamath/configuration-properties
          clone-on-start: true
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://myeureka-server.herokuapp.com/eureka